# Deployment manifest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testops-deployment
  labels:
    app: test

spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: testops
          image: testops:0.1
          env:
            - name: PORT
              value: "8081"
            - name: IP_ADDR
              value: "0.0.0.0"

# Service manifest
---
apiVersion: v1
kind: Service
metadata:
  name: testops-service

spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

# Execute below command to forward localhost:port traffic tp service clusterIP
# kubectl port-forward service/testops-service 8080:8080